apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters 
      rolearn : arn:aws:iam::981557710771:role/UdacityFlaskDeployCBKubectlRole 
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981557710771:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RVVAJ3Z7VBAB
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-24T09:18:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1386"
  uid: 783867f3-dd27-476d-8cbc-400b0305730c
